In [1]:
# =======================================================================
# Exercise: Variables in Python
# Course: Deep Learning Complete Course (CS-501)
#
# Description: This notebook contains 20 questions/exercises to test
#              your understanding of creating, naming, and using variables
#              in Python.
# ¬© Copyright: Dr. Saad Laouadi
# All Rights Reserved üõ°Ô∏è
# =======================================================================

In [19]:
# Q1: Create a variable named `age` and assign your age to it.
# Your code here:

print("*"*60)
age = 35
print("My age is:",age,"years")
print("*"*60)

# Q2: Create two variables, `city` and `country`, and assign your city and country to them.
# Your code here:

city = "si_mustapha" 
country = "algeria"
print("My city:",city)
print("My Country:",country)
print("*"*60)


# Q3: Combine `city` and `country` into a single string `location` and print it.
# Your code here:

city = "si_mustapha"
country = "algeria"
print("City:",city,"and","Country:",country)
print("*"*60)

# Q4: Change the value of `age` to a different number and print it.
# Your code here:

age = 28
print("Diffrent age:",age,"years")
print("*"*60)


# Q5: Create a variable `height` and assign a float value representing your height in meters.
# Your code here:

height = 1.72
print("My height:",height,"m")
print("*"*60)

# Q6: Check and print the data type of the `height` variable using the `type()` function.
# Your code here:

height = 1.72
print("The data type of the 'height':",type((height)))
print("*"*60)
      


# Q7: Assign the value `True` to a variable named `is_student` and print the variable.
# Your code here:

is_student = True
print("Is Student:",is_student)
print("*"*60)

# Q8: Create a variable `name` with your first name using double quotes and then another variable `surname` with your last name using single quotes. Combine them into `full_name`.
# Your code here:

name = "BENOUADAH"
surname = 'djamel'
full_name = "BENOUADAH djamel"
print("My name is:",name)
print("My surname is:",surname)
print("Combine the full name:",name,surname)
              # In another way
print("*"*40)
print("Combine the full name:",full_name)
print("*"*60)


# Q9: Create two variables `x` and `y` and assign them integer values. Swap their values without using a third variable.
# Your code here:

x = 5
y = 10
print("x=",x)
print("y=",y)
print("*"*10)
print("x=",y)
print("y=",x)
print("*"*60)


# Q10: Write a statement to update the `age` variable by adding 5 to it.
# Your code here:

age = 35
adding_5 = age + 5
print(age)
print("Age is:",adding_5)
      #  In another way
print("*"*10)
age = 35
print("Age is:",age)
age += 5
print("ŸéAge after adding 5:",age)
print("*"*60)




# Q11: Create a variable `length` and assign it the value 15. Create another variable `width` and assign it 10. Calculate the area of a rectangle using thise variables and print the result.
# Your code here:


length = 15
width = 10
area = length*width
print("The area of a rectangles:",area)



# Q12: Using the variables `base` and `height`, calculate the area of a triangle and print it. Assume `base = 8` and `height = 5`.
# Your code here:

print("*"*60)
base = 8
heigth = 5
area_tr = 0.5*base*heigth
print("The area of a triangle:",area_tr) 


# Q13: Create a string variable `greeting` with the text "Hello" and another variable `recipient` with the text "World". Combine them with a space in between and print the result.
# Your code here:

print("*"*60)
greeting = "hello"
recipient = "world"
print(greeting + " " + recipient)


# Q14: Create a boolean variable `is_active` and set it to `False`. Then change its value to `True` and print it.
# Your code here:

print("*"*60)
is_active = False
is_active = True
print(is_active)


# Q15: Using f-strings, print a formatted message: "My name is [name] and I am [age] years old." Replace [name] and [age] with the appropriate variables.
# Your code here:

print("*"*69)
name = "djamel BENOUADAH"
age = 35
formatted_string = f"My name is {name} and I am {age} years old"
print("formatted string: ", formatted_string)



# Q16: Create a variable `pi` and assign it the value 3.14159. Print the variable, ensuring it only shows 2 decimal places.
# Your code here:

print("*"*69)
pi = 3.14159
print(round(pi,2))



# Q17: Assign the value of a mathematical expression (e.g., `2 * (3 + 5)`) to a variable and print it.
# Your code here:

print("*"*60)
x= 2
y= 3
z= 5
j= x*(y+z)
print(j)


# Q18: Create a variable `sentence` and assign it a sentence of your choice. Use slicing to print the first 5 characters.
# Your code here:

print("*"*60)
sentence= "Thank God"
print(sentence[:5])

# Q19: Create a variable `number` with the value 100. Use an arithmetic operation to double its value and then print it.
# Your code here:

print("*"*60)
number= 100
double= number*2
print("value: ",number)
print("double value: ",double)




# Q20: Declare three variables `a`, `b`, and `c` with values 5, 10, and 15 respectively. Calculate and print their average.
# Your code here:

print("*"*60)
a= 5
b= 10
c= 15
average= (a+b+c)/3
print("average: ",average)
print("*"*60)
print("thank you D.Saad")
# =======================================================================
# End of Exercise
# =======================================================================

************************************************************
My age is: 35 years
************************************************************
My city: si_mustapha
My Country: algeria
************************************************************
City: si_mustapha and Country: algeria
************************************************************
Diffrent age: 28 years
************************************************************
My height: 1.72 m
************************************************************
The data type of the 'height': <class 'float'>
************************************************************
Is Student: True
************************************************************
My name is: BENOUADAH
My surname is: djamel
Combine the full name: BENOUADAH djamel
****************************************
Combine the full name: BENOUADAH djamel
************************************************************
x= 5
y= 10
**********
x= 10
y= 5
************************************************************
35
Age is: 40
**********
Age is: 35
ŸéAge after adding 5: 40
************************************************************
The area of a rectangles: 150
************************************************************
The area of a triangle: 20.0
************************************************************
hello world
************************************************************
True
*********************************************************************
formatted string:  My name is djamel BENOUADAH and I am 35 years old
*********************************************************************
3.14
************************************************************
16
************************************************************
Thank
************************************************************
value:  100
double value:  200
************************************************************
average:  10.0

TypeError: unsupported operand type(s) for -: 'str' and 'int'